"""Signal 1: Groq LLM classifier — holistic semantic/stylistic assessment."""
import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a text-provenance analyst. Given a passage of text, assess the "
    "probability that it was generated by an AI language model rather than "
    "written by a human, based on semantic and stylistic coherence — tone, "
    "voice, hedging, idiosyncrasy, and overall fluency. Respond with ONLY a "
    'JSON object of the form {"p_ai": <float between 0 and 1>, "reasoning": '
    '"<one sentence>"}. Do not include any text outside the JSON object.'
)

_client = None


class LLMSignalError(Exception):
    """Raised when the Groq signal cannot be produced (API error or bad output)."""


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise LLMSignalError("GROQ_API_KEY is not set")
        _client = Groq(api_key=api_key)
    return _client


def get_llm_signal(text):
    """Return {"p_ai": float in [0,1], "reasoning": str} for the given text."""
    client = _get_client()
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            response_format={"type": "json_object"},
            temperature=0.0,
        )
        raw = response.choices[0].message.content
    except Exception as exc:
        raise LLMSignalError(f"Groq request failed: {exc}") from exc

    try:
        parsed = json.loads(raw)
        p_ai = float(parsed["p_ai"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise LLMSignalError(f"Groq returned unparseable output: {raw!r}") from exc

    p_ai = max(0.0, min(1.0, p_ai))
    return {"p_ai": p_ai, "reasoning": parsed.get("reasoning", "")}
